apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-a
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-a
  template:
    metadata:
      labels:
        msePilotAutoEnable: "on"
        appName: "{{ .Release.Namespace }}-sc-a"
        app: "sc-a"
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: sc-a
          image: "{{ .Values.registry }}spring-cloud-a:1.0.0"
          imagePullPolicy: Always
          env:
            - name: nacos.host
              value: "{{ .Values.nacos.host }}"
            - name: nacos.namespace
              value: "{{ .Values.nacos.namespace }}"
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
          ports:
            - name: http-port
              containerPort: 20001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 50
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 100
