apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-b
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-b
  template:
    metadata:
      labels:
        msePilotAutoEnable: "on"
        appName: "{{ .Release.Namespace }}-sc-b"
        app: "sc-b"
    spec:
      containers:
        - name: sc-b
          image: "{{ .Values.registry }}spring-cloud-b:1.0.0"
          imagePullPolicy: Always
          env:
            - name: nacos.host
              value: "{{ .Values.nacos.host }}"
            - name: nacos.namespace
              value: "{{ .Values.nacos.namespace }}"
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
          ports:
            - name: http-port
              containerPort: 20002
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 50
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 100
